### ISSUE TITLE
Can't run on preBuild - http://localhost:8888 timed out on retry 31 of 1

### ISSUE THREAD

**Issue by princefishthrower** [cypress-io/netlify-plugin-prebuild-example#193]
I've tried both `gatsby develop` with `localhost:8000` and `netlify dev` with `localhost:8888`, cypress isn't able to connect with either during my pipeline. What am I doing wrong here? Preferrably I would like to use the `netlify dev` configuration:

```toml
[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"
  # let's first test the site before Gatsby builds it
  [plugins.inputs.preBuild]
    enable = true
    start = 'netlify dev'
    wait-on = 'http://localhost:8888'
    wait-on-timeout = '30' # seconds
    record = true
    group = '1: testing develop site'

  # then Netlify builds the site
  # and then our tests will run again, testing the built production version
  [plugins.inputs.postBuild]
    # investigating why preBuild server has not been stopped
    # https://github.com/cypress-io/netlify-plugin-cypress/issues/119
    enable = true
    record = true
    group = '2: testing built site'

  # do not test the deployed URL
  [plugins.inputs]
    enable = false
```
